tsadm/jobq/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('',
    url(r'^get/([a-f0-9]+)/$', 'tsadm.jobq.views.get', name='get'),
    url(r'^end/([a-f0-9]+)/$', 'tsadm.jobq.views.end', name='end'),
    url(r'^update/([a-f0-9]+)/$', 'tsadm.jobq.views.update', name='update'),

    url(r'^(\w+)/(\w+)/info/([a-f0-9]+)/$', 'tsadm.jobq.views.info', name='info'),

    url(r'^icc/(\w+)/(\w+)/([\w.-]+)/$', 'tsadm.jobq.views.intcmd_confirm', name='intcmd_confirm'),
    url(r'^ice/(\w+)/(\w+)/([\w.-]+)/$', 'tsadm.jobq.views.intcmd_exec', name='intcmd_exec'),

    url(r'^cc/(\w+)/(\w+)/$', 'tsadm.jobq.views.cmd_confirm', name='cmd_confirm'),
    url(r'^ce/(\w+)/(\w+)/$', 'tsadm.jobq.views.cmd_exec', name='cmd_exec'),
)

tsadm/site/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('',
    url(r'^admin/$', 'tsadm.site.views.admin', name='admin'),

    url(r'^index/$', 'tsadm.site.views.index', name='index'),
    url(r'^(\w+)/(\w+)/$', 'tsadm.site.views.dashboard', name='dashboard'),

    url(r'^(\w+)/(\w+)/log/$', 'tsadm.site.views.log', name='log'),

    url(r'^(\w+)/(\w+)/lock/$', 'tsadm.site.views.lock_confirm', name='lock_confirm'),
    url(r'^(\w+)/(\w+)/lock/([a-f0-9]+)/$', 'tsadm.site.views.lock', name='lock'),

    url(r'^(\w+)/(\w+)/unlock/$', 'tsadm.site.views.unlock_confirm', name='unlock_confirm'),
    url(r'^(\w+)/(\w+)/unlock/([a-f0-9]+)/$', 'tsadm.site.views.unlock', name='unlock'),

    url(r'^(\w+)/(\w+)/claim/$', 'tsadm.site.views.claim_confirm', name='claim_confirm'),
    url(r'^(\w+)/(\w+)/claim/([a-f0-9]+)/$', 'tsadm.site.views.claim', name='claim'),

    url(r'^(\w+)/(\w+)/release/$', 'tsadm.site.views.release_confirm', name='release_confirm'),
    url(r'^(\w+)/(\w+)/release/([a-f0-9]+)/$', 'tsadm.site.views.release', name='release'),

    url(r'^envRedir/$', 'tsadm.site.views.env_redir', name='envRedir'),
)

tsadm/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('',
    url(r'^$', 'tsadm.site.views.index', name='index'),
    url(r'^soft-info/$', 'tsadm.views.soft_info', name='soft-info'),

    url(r'^cmd/confirm/$', 'tsadm.views.cmd_confirm', name='cmd_confirm'),
    url(r'^cmd/exec/$', 'tsadm.views.cmd_exec', name='cmd_exec'),

    url(r'^admin/', include('tsadm.admin.urls', namespace='admin')),
    url(r'^site/', include('tsadm.site.urls', namespace='site')),
    url(r'^git/', include('tsadm.git.urls', namespace='git')),
    url(r'^files/', include('tsadm.rsync.urls', namespace='rsync')),
    url(r'^db/', include('tsadm._mysql.urls', namespace='mysql')),
    url(r'^jobq/', include('tsadm.jobq.urls', namespace='jobq')),
    url(r'^help/', include('tsadm.help.urls', namespace='help')),
    url(r'^user/', include('tsadm.user.urls', namespace='user')),
    url(r'^slave/', include('tsadm.slave.urls', namespace='slave')),
    url(r'^asb/', include('tsadm.ansible.urls', namespace='ansible')),
)

tsadm/jobq/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse

import json
import time
import gzip
from base64 import b64decode, b64encode

from tsadm.jobq.cmd import TSAdmJobQCmdInvoke, TSAdmJobQCmdNotFound
from tsadm.jobq.intcmd import TSAdmJobQIntCmdInvoke

from tsadm.git.jobq import GIT_CMD_MAP
from tsadm.rsync.jobq import RSYNC_CMD_MAP
from tsadm._mysql.jobq import MYSQL_CMD_MAP

from tsadm.wapp import TSAdmWApp
wapp = TSAdmWApp()


def get(req, job_id):
    if not wapp.start(req, '__jobq/get', '__jobq/get', acclvl='HOST'):
        return wapp.error_page()

    job_info = wapp.db.jobq_get(job_id)
    wapp.log.dbg('job_info: ', job_info)

    resp_status = 404
    if job_info is not None:
        resp_status = 200

    resp = HttpResponse(json.dumps(job_info), content_type='text/plain; charset=utf-8', status=resp_status)
    wapp.end()
    return resp


def end(req, job_id):
    if not wapp.start(req, '__jobq/end', '__jobq/end', acclvl='HOST'):
        return wapp.error_page()
    wapp.log.dbg('method: ', req.method)

    resp_status = 400
    resp_body = ';-)\n'

    if req.method == 'POST':
        # FIXME: check current status is not END and that job_id exists!!
        cmd_rtrn = req.POST.get('cmd_rtrn', None)
        cmd_out = req.POST.get('cmd_out', None)
        if cmd_rtrn is None or cmd_out is None:
            wapp.log.dbg('jobq.end cmd_rtrn: ', cmd_rtrn)
            wapp.log.dbg('jobq.end cmd_out: ', cmd_out)
            wapp.log.err('jobq.end: bad post data')
            resp_body = ':-(\n'
        else:
            wapp.jobq.end(job_id, cmd_rtrn, cmd_out, compress=False, encode=False)
            resp_status = 200
            resp_body = ':-)\n'
            wapp.log.dbg('jobq.end: done')
    else:
        wapp.log.err('jobq.end: only POSTs allowed')

    resp = HttpResponse(resp_body, content_type='text/plain; charset=utf-8', status=resp_status)
    wapp.end()
    return resp


def info(req, sname, senv, job_id):
    if not wapp.start(req, sname, senv):
        return wapp.error_page()
    tmpl_data = wapp.tmpl_data()

    job_info = wapp.db.jobq_get_info(wapp.site.env.id, job_id)
    if job_info is None:
        return wapp.error_page(404, 'NO JOB INFO')
    else:
        tmpl_data.update(job_info)
        try:
            tmpl_data['cmd_output'] = gzip.decompress(b64decode(job_info.get('cmd_output', '').encode('utf-8', 'replace'))).decode()
        except Exception as e:
            wapp.log.err('jobq.info: ', e)
            tmpl_data['cmd_output'] = 'INTERNAL ERROR: could not read data'
        tmpl_data['tstamp_start'] = time.strftime(wapp.conf.get('JOB_DATE_FMT'), time.localtime(int(job_info.get('tstamp_start', 0))))

        tse = int(job_info.get('tstamp_end', 0))
        if tse > 0:
            tmpl_data['tstamp_end'] = time.strftime(wapp.conf.get('JOB_DATE_FMT'), time.localtime(tse))
        else:
            tmpl_data['tstamp_end'] = '...'

        tmpl_data['css_class'] = 'error'
        cmd_rtrn = job_info.get('cmd_rtrn', 92)
        wapp.log.dbg('cmd_rtrn: ', cmd_rtrn)

        if cmd_rtrn == 0:
            tmpl_data['css_class'] = 'ok'
        elif cmd_rtrn == 9999:
            tmpl_data['css_class'] = 'start'
        elif cmd_rtrn == 9090:
            tmpl_data['css_class'] = 'run'

    return render(req, 'jobq/info.html', wapp.end(tmpl_data))


def update(req, job_id):
    if not wapp.start(req, '__jobq/update', '__jobq/update', acclvl='HOST'):
        return wapp.error_page()
    wapp.log.dbg('method: ', req.method)

    resp_status = 400
    resp_body = ';-)\n'

    if req.method == 'POST':
        job_status = req.POST.get('job_status', None)
        if job_status is None:
            wapp.log.dbg('jobq.update job_status: ', job_status)
            wapp.log.err('jobq.update: bad post data')
            resp_body = ':-(\n'
        else:
            wapp.jobq.status_update(job_id, job_status)
            resp_status = 200
            resp_body = ':-)\n'
            wapp.log.dbg('jobq.update: ', job_status, ' done')
    else:
        wapp.log.err('jobq.update: only POSTs allowed')

    resp = HttpResponse(resp_body, content_type='text/plain; charset=utf-8', status=resp_status)
    wapp.end()
    return resp


def intcmd_confirm(req, sname, senv, cmd_name):
    if not wapp.start(req, sname, senv):
        return wapp.error_page()
    tmpl_data = wapp.tmpl_data()
    tmpl_data['cmd'] = {
        'name': cmd_name
    }
    return render(req, 'jobq/intcmd_confirm.html', wapp.end(tmpl_data))


def intcmd_exec(req, sname, senv, cmd_name):
    if not wapp.start(req, sname, senv):
        return wapp.error_page()
    intcmd = TSAdmJobQIntCmdInvoke(cmd_name, wapp)
    jobq_id = intcmd.execute()
    wapp.end()
    return redirect('jobq:info', sname, senv, jobq_id)


def __cmd_args_post_load(POST):
    cmd_args = ''
    for ak, av in POST.items():
        if ak.startswith('tsadm_') and (ak != 'tsadm_cmd' and ak != 'tsadm_return_to'):
            cmd_args = '{} --{}={}'.format(cmd_args, ak.replace('tsadm_', '', 1), av)
    return cmd_args.lstrip()


def cmd_confirm(req, sname, senv):
    if not wapp.start(req, sname, senv):
        return wapp.error_page()
    cmd_name = req.POST.get('tsadm_cmd', None)
    if cmd_name is None:
        return wapp.error_page(500, 'no command name')
    return_to = req.POST.get('tsadm_return_to', '/return_to-non-set')
    cmd_args = __cmd_args_post_load(req.POST)
    cmd_args_encode = b64encode(cmd_args.encode()).decode()
    tmpl_data = wapp.tmpl_data()
    tmpl_data['return_to'] = return_to
    tmpl_data['cmd'] = {
        'name': cmd_name,
        'args': cmd_args,
        'args_encode': cmd_args_encode,
    }
    return render(req, 'jobq/cmd_confirm.html', wapp.end(tmpl_data))


def cmd_exec(req, sname, senv):
    if not wapp.start(req, sname, senv):
        return wapp.error_page()
    # -- cmd name
    cmd_name = req.POST.get('tsadm_cmd', None)
    if cmd_name is None:
        return wapp.error_page(500, 'no command name')
    # -- cmd args
    cmd_args_encode = req.POST.get('tsadm_cmd_args_encode', None)
    cmd_args = ''
    if cmd_args_encode is not None:
        cmd_args = b64decode(cmd_args_encode.encode())
    # -- cmd map
    cmd_map = dict()
    cmd_map.update(GIT_CMD_MAP)
    cmd_map.update(RSYNC_CMD_MAP)
    cmd_map.update(MYSQL_CMD_MAP)
    # -- exec cmd
    try:
        cmd = TSAdmJobQCmdInvoke(cmd_map, cmd_name, wapp)
    except TSAdmJobQCmdNotFound:
        return wapp.error_page(501, 'command not implemented: '+cmd_name)
    jobq_id = cmd.execute(cmd_args)
    # -- end
    wapp.end()
    return redirect('jobq:info', sname, senv, jobq_id)

templates/jobq/cmd_confirm.html
{% include "inc/head.html" %}
<!-- START: jobq/cmd_confirm -->
<p>
    Confirm running command against <b>{{site.name}}.{{site.env.name}}</b> environment.<br />
    <b>{{cmd.name}} {{cmd.args}}</b><br />
</p>
<p>
    <form class="inline" action="{% url 'jobq:cmd_exec' site.name site.env.name %}" method="post">
        <input type="hidden" name="tsadm_cmd_args_encode" value="{{cmd.args_encode}}">
        <input type="hidden" name="tsadm_cmd" value="{{cmd.name}}">
        <input class="button" type="submit" value="confirm">
    </form>
    <form class="inline" action="{{return_to}}" method="post">
        <input class="button" type="submit" value="cancel">
    </form>
</p>
<!-- END: jobq/cmd_confirm -->
{% include "inc/tail.html" %}

templates/jobq/info.html
{% include "inc/head.html" %}
<!-- START: jobq/info -->

<p><a href="{% url 'site:log' site.name site.env.name %}">site log</a> - <a href="{{page.uri}}">refresh</a></p>

<ul>
    <li>{{tstamp_start}}</li>
    <li>{{cmd_name}}
    {% if cmd_args != '' %}
        <ul><li>{{cmd_args}}</li></ul>
    {% endif %}
    </li>
    <li>{{user_name}}</li>
    <li>{{sname}}.{{senv}}</li>
    <li>{{status}}:{{cmd_rtrn}}</li>
    <li>{{tstamp_end}}</li>
</ul>

<pre class="cmd-output-{{css_class}}">
{{cmd_output}}
</pre>

<!-- CMD_STATUS={{cmd_name}}:{{cmd_rtrn}} -->
<!-- END: jobq/info -->
{% include "inc/tail.html" %}

templates/jobq/intcmd_confirm.html
{% include "inc/head.html" %}
<!-- START: jobq/intcmd_confirm -->
<p>Confirm running command against <b>{{site.name}}.{{site.env.name}}</b> environment: <a href="{% url 'jobq:intcmd_exec' site.name site.env.name cmd.name %}">{{cmd.name}}</a></p>
<!-- END: jobq/intcmd_confirm -->
{% include "inc/tail.html" %}

templates/jobq/run.html
{% include "inc/head.html" %}
<!-- START: jobq/run -->

<!-- show command status and output -->
<p><h2>{{cmd.name}}:{{cmd.rtrn}}</h2> - <a href="{% url 'site:dashboard' site.name site.env.name %}#activity-log">view activity log</a></p>

<pre class="cmd-output-{{css_class}}">
{{cmd.output}}
</pre>

<!-- END: jobq/run -->
{% include "inc/tail.html" %}

templates/jobq/run_confirm.html
{% include "inc/head.html" %}
<!-- START: jobq/run_confirm -->
<p>Confirm running command: <b>{{cmd.name}}</b></p>
<p>
    <form class="inline" action="{% url 'jobq:run' site.name site.env.name %}" method="post">
    {% for ak, av in cmd.args.items %}
        <input type="hidden" name="{{ak}}" value="{{av}}">
    {% endfor %}
        <input type="hidden" name="tsadm_cmd_runbg" value="TRUE">
        <input type="hidden" name="tsadm_cmd" value="{{cmd.name}}">
        <input class="button" type="submit" value="confirm">
    </form>
    <form class="inline" action="{{jobq_return_to}}" method="post">
        <input class="button" type="submit" value="cancel">
    </form>
</p>
<!-- END: jobq/run_confirm -->
{% include "inc/tail.html" %}