tsadm/git/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('',
    url(r'^(\w+)/(\w+)/$', 'tsadm.git.views.home', name='home'),
    url(r'^hook/post-receive/$', 'tsadm.git.views.post_receive', name='post_receive'),
)

tsadm/help/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('',
    url(r'^(\w+)/(\w+)/$', 'tsadm.help.views.site', name='site'),
)

tsadm/jobq/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('',
    url(r'^get/([a-f0-9]+)/$', 'tsadm.jobq.views.get', name='get'),
    url(r'^end/([a-f0-9]+)/$', 'tsadm.jobq.views.end', name='end'),
    url(r'^update/([a-f0-9]+)/$', 'tsadm.jobq.views.update', name='update'),

    url(r'^(\w+)/(\w+)/info/([a-f0-9]+)/$', 'tsadm.jobq.views.info', name='info'),

    url(r'^icc/(\w+)/(\w+)/([\w.-]+)/$', 'tsadm.jobq.views.intcmd_confirm', name='intcmd_confirm'),
    url(r'^ice/(\w+)/(\w+)/([\w.-]+)/$', 'tsadm.jobq.views.intcmd_exec', name='intcmd_exec'),

    url(r'^cc/(\w+)/(\w+)/$', 'tsadm.jobq.views.cmd_confirm', name='cmd_confirm'),
    url(r'^ce/(\w+)/(\w+)/$', 'tsadm.jobq.views.cmd_exec', name='cmd_exec'),
)

tsadm/site/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('',
    url(r'^admin/$', 'tsadm.site.views.admin', name='admin'),

    url(r'^index/$', 'tsadm.site.views.index', name='index'),
    url(r'^(\w+)/(\w+)/$', 'tsadm.site.views.dashboard', name='dashboard'),

    url(r'^(\w+)/(\w+)/log/$', 'tsadm.site.views.log', name='log'),

    url(r'^(\w+)/(\w+)/lock/$', 'tsadm.site.views.lock_confirm', name='lock_confirm'),
    url(r'^(\w+)/(\w+)/lock/([a-f0-9]+)/$', 'tsadm.site.views.lock', name='lock'),

    url(r'^(\w+)/(\w+)/unlock/$', 'tsadm.site.views.unlock_confirm', name='unlock_confirm'),
    url(r'^(\w+)/(\w+)/unlock/([a-f0-9]+)/$', 'tsadm.site.views.unlock', name='unlock'),

    url(r'^(\w+)/(\w+)/claim/$', 'tsadm.site.views.claim_confirm', name='claim_confirm'),
    url(r'^(\w+)/(\w+)/claim/([a-f0-9]+)/$', 'tsadm.site.views.claim', name='claim'),

    url(r'^(\w+)/(\w+)/release/$', 'tsadm.site.views.release_confirm', name='release_confirm'),
    url(r'^(\w+)/(\w+)/release/([a-f0-9]+)/$', 'tsadm.site.views.release', name='release'),

    url(r'^envRedir/$', 'tsadm.site.views.env_redir', name='envRedir'),
)

tsadm/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('',
    url(r'^$', 'tsadm.site.views.index', name='index'),
    url(r'^soft-info/$', 'tsadm.views.soft_info', name='soft-info'),

    url(r'^cmd/confirm/$', 'tsadm.views.cmd_confirm', name='cmd_confirm'),
    url(r'^cmd/exec/$', 'tsadm.views.cmd_exec', name='cmd_exec'),

    url(r'^admin/', include('tsadm.admin.urls', namespace='admin')),
    url(r'^site/', include('tsadm.site.urls', namespace='site')),
    url(r'^git/', include('tsadm.git.urls', namespace='git')),
    url(r'^files/', include('tsadm.rsync.urls', namespace='rsync')),
    url(r'^db/', include('tsadm._mysql.urls', namespace='mysql')),
    url(r'^jobq/', include('tsadm.jobq.urls', namespace='jobq')),
    url(r'^help/', include('tsadm.help.urls', namespace='help')),
    url(r'^user/', include('tsadm.user.urls', namespace='user')),
    url(r'^slave/', include('tsadm.slave.urls', namespace='slave')),
    url(r'^asb/', include('tsadm.ansible.urls', namespace='ansible')),
)

tsadm/site/views.py
import os
import time

from django.shortcuts import render, redirect

from tsadm.wapp import TSAdmWApp
wapp = TSAdmWApp()

from . import envs_all


def index(req):
    if not wapp.start(req, '__site/index', '__site/index'):
        return wapp.error_page()

    regrt_data = list()
    sites_no = 0
    envs_no = 0
    s_all = wapp.db.site_all()
    se_all = list()
    for s in s_all:
        sites_no += 1
        show_site = False
        sd = dict()
        sd['name'] = s[1]
        sd['parent_site'] = dict()
        if s[2] != 0:
            sd['parent_site'] = wapp.db.site_info(s[2])
        envs = wapp.db.siteenv_all(s[0])
        sd['envs'] = list()
        for e in envs:
            envs_no += 1
            if e['id'] in wapp.user.siteenv_acl or 0 in wapp.user.siteenv_acl:
                if sd['name'] == 'regr':
                    if e['name'] == 'dev' or e['name'] == 'test':
                        regrt_data.append(sd['name'] + e['name'])
                ed = dict()
                ed.update(e)
                if ed['locked']:
                    if e['locked_by'] == wapp.user.name:
                        ed['locked_by'] = 'you'
                if ed['claimed']:
                    if e['claimed_by'] == wapp.user.name:
                        ed['claimed_by'] = 'you'
                sd['envs'].append(ed)
                show_site = True
        if show_site:
            se_all.append(sd)

    tmpl_data = wapp.tmpl_data()
    tmpl_data['se_all'] = se_all
    tmpl_data['sites_no'] = sites_no
    tmpl_data['envs_no'] = envs_no
    tmpl_data.update(wapp.tmpl_regr_tests_data(regrt_data))
    return render(req, 'site/index.html', wapp.end(tmpl_data))


def dashboard(req, sname, senv, wapp_start=True):
    if wapp_start:
        if not wapp.start(req, sname, senv):
            return wapp.error_page()
    tmpl_data = wapp.tmpl_data()
    # -- jobq log
    tmpl_data['jobq'] = dict()
    tmpl_data['jobq']['log'] = list()
    db_log = wapp.db.jobq_senv_all(wapp.site.env.id)
    for dbe in db_log:
        dbe['id_slug'] = '{}...{}'.format(dbe['id'][:7], dbe['id'][-7:])
        if dbe['cmd_exit'] == 0:
            dbe['css_class'] = 'ok'
        elif dbe['cmd_exit'] == 9999:
            dbe['css_class'] = 'start'
        elif dbe['cmd_exit'] == 9090:
            dbe['css_class'] = 'run'
        else:
            dbe['css_class'] = 'error'
        if dbe['status'] == 'END':
            dbe['cmd_took'] = '{}s'.format(dbe['tstamp_end'] - dbe['tstamp_start'])
        else:
            dbe['cmd_took'] = '.'
        dbe['date'] = time.strftime(wapp.conf.get('LOG_DATE_FMT'), time.localtime(dbe['tstamp_start']))
        tmpl_data['jobq']['log'].append(dbe)
    del db_log
    # child site?
    if wapp.site.parent_id > 0:
        wapp.umesg.inf('child installation of site: {}'.format(wapp.site.parent_site['name']))
    return render(req, 'site/dashboard.html', wapp.end(tmpl_data))


def lock_confirm(req, sname, senv):
    if not wapp.start(req, sname, senv):
        return wapp.error_page()
    tmpl_data = wapp.tmpl_data()
    jobr_id = wapp.jobq.idgen()
    tmpl_data['lock'] = dict()
    tmpl_data['lock']['jobr_id'] = jobr_id
    wapp.db.siteenv_lock_req(wapp.site.env.id, jobr_id, wapp.user.id)
    return render(req, 'site/lock_confirm.html', wapp.end(tmpl_data))


def lock(req, sname, senv, confirm):
    if not wapp.start(req, sname, senv):
        return wapp.error_page()
    tmpl_data = wapp.tmpl_data()
    jid = wapp.jobq.start('env.lock', '')
    wapp.db.siteenv_lock(wapp.site.env.id, confirm, wapp.user.id)
    wapp.jobq.end(jid, 0, 'env locked')
    tmpl_data['load_sites_navbar'] = False
    return render(req, 'site/locked.html', wapp.end(tmpl_data))


def unlock_confirm(req, sname, senv):
    if not wapp.start(req, sname, senv, unlock_req=True):
        return wapp.error_page()
    tmpl_data = wapp.tmpl_data()
    jobr_id = wapp.jobq.idgen()
    tmpl_data['unlock'] = dict()
    tmpl_data['unlock']['jobr_id'] = jobr_id
    wapp.db.siteenv_unlock_req(wapp.site.env.id, jobr_id)
    return render(req, 'site/unlock_confirm.html', wapp.end(tmpl_data))


def unlock(req, sname, senv, jobr_id):
    if not wapp.start(req, sname, senv, unlock_req=True):
        return wapp.error_page()
    jid = wapp.jobq.start('env.unlock', '')
    wapp.db.siteenv_unlock(wapp.site.env.id, jobr_id, wapp.user.id)
    wapp.jobq.end(jid, 0, 'env unlocked')
    wapp.end()
    return redirect('site:dashboard', sname, senv)


def claim_confirm(req, sname, senv):
    if not wapp.start(req, sname, senv):
        return wapp.error_page()
    tmpl_data = wapp.tmpl_data()
    jobr_id = wapp.jobq.idgen()
    tmpl_data['jobr_id'] = jobr_id
    wapp.db.siteenv_claim_req(jobr_id, wapp.user.id, wapp.site.env.id)
    return render(req, 'site/claim_confirm.html', wapp.end(tmpl_data))


def claim(req, sname, senv, confirm):
    if not wapp.start(req, sname, senv):
        return wapp.error_page()
    jid = wapp.jobq.start('env.claim', '')
    wapp.db.siteenv_claim(wapp.site.env.id, confirm, wapp.user.id)
    wapp.jobq.end(jid, 0, 'env claimed')
    wapp.end()
    return redirect('site:dashboard', sname, senv)


def release_confirm(req, sname, senv):
    if not wapp.start(req, sname, senv):
        return wapp.error_page()
    tmpl_data = wapp.tmpl_data()
    jobr_id = wapp.jobq.idgen()
    tmpl_data['jobr_id'] = jobr_id
    wapp.db.siteenv_release_req(jobr_id, wapp.user.id, wapp.site.env.id)
    return render(req, 'site/release_confirm.html', wapp.end(tmpl_data))


def release(req, sname, senv, confirm):
    if not wapp.start(req, sname, senv):
        return wapp.error_page()
    jid = wapp.jobq.start('env.release', '')
    wapp.db.siteenv_release(wapp.site.env.id, confirm, wapp.user.id)
    wapp.jobq.end(jid, 0, 'env released')
    wapp.end()
    return redirect('site:dashboard', sname, senv)


def log(req, sname, senv):
    if not wapp.start(req, sname, senv):
        return wapp.error_page()
    tmpl_data = wapp.tmpl_data()
    site_log = list()
    for le in wapp.db.site_log(wapp.site.id):
        d = {
            'date': time.strftime(wapp.conf.get('LOG_DATE_FMT'), time.localtime(le['tstamp_start'])),
            'cmd_took': '.',
            'id_slug': '{}...{}'.format(le['id'][:7], le['id'][-7:]),
        }
        if le['status'] == 'END':
            d['cmd_took'] = '{}s'.format(le['tstamp_end'] - le['tstamp_start'])
        if le['cmd_exit'] == 0:
            d['css_class'] = 'ok'
        elif le['cmd_exit'] == 9999:
            d['css_class'] = 'start'
        elif le['cmd_exit'] == 9090:
            d['css_class'] = 'run'
        else:
            d['css_class'] = 'error'
        le.update(d)
        site_log.append(le)
    tmpl_data['site']['log'] = site_log
    return render(req, 'site/log.html', wapp.end(tmpl_data))


def admin(req):
    if not wapp.start(req, '__site/admin', acclvl='SITE_ADMIN'):
        return wapp.error_page()
    tmpl_data = wapp.tmpl_data()
    tmpl_data['envs_all'] = envs_all(wapp)
    tmpl_data['admin'] = {
        'cmds': ['site.checks', 'lalala'],
    }
    return render(req, 'site/admin.html', wapp.end(tmpl_data))


def env_redir(req):
    if not wapp.start(req, '__site/envRedir'):
        return wapp.error_page()
    envRedir = req.POST.get('tsadmEnvRedir', None)
    if envRedir is None or envRedir == '':
        return wapp.error_page(400, 'invalid request -1')
    try:
        sName = envRedir.split('.')[0]
        eName = envRedir.split('.')[1]
    except IndexError:
        return wapp.error_page(400, 'invalid request -2')
    return redirect('site:dashboard', sName, eName)

templates/site/admin.html
{% include "inc/head.html" %}
<!-- START: site/admin -->
<div id="site-admin">
    <form action="{% url 'cmd_confirm' %}" method="POST">
        <select class="button" name="tsadm_site_env">
        {% for senv in envs_all %}
            <option value="{{senv.id}}">{{senv.slug}}</option>
        {% endfor %}
        </select>
        <select class="button" name="tsadm_cmd">
        {% for cmd in admin.cmds %}
            <option value="{{cmd}}">{{cmd}}</option>
        {% endfor %}
        </select>
        <input type="hidden" name="tsadm_return_to" value="{% url 'site:admin' %}">
        <input class="button" type="submit" value="run">
    </form>
</div>
<!-- END: site/admin -->
{% include "inc/tail.html" %}

templates/site/cant_unlock.html
{% include "inc/head.html" %}
<!-- START: site/cant_unlock -->
<p><b>{{site.name}}.{{site.env.name}}</b> is locked</p>
<p>Locked by: {{site.env.locked_by}}</p>
<!-- END: site/cant_lock -->
{% include "inc/tail.html" %}

templates/site/claim_confirm.html
{% include "inc/head.html" %}
<!-- START: site/claim_confirm -->
<p>Confirm claiming <b>{{site.name}}.{{site.env.name}}</b> environment: <a href="{% url 'site:claim' site.name site.env.name jobr_id %}">claim.confirm</a></p>
<!-- END: site/claim_confirm -->
{% include "inc/tail.html" %}

templates/site/claimed.html
{% include "inc/head.html" %}
<!-- START: site/claimed -->
<p><b>{{site.name}}.{{site.env.name}}</b> is claimed by {{site.env.claimed_by}}</p>
<!-- END: site/claimed -->
{% include "inc/tail.html" %}

templates/site/dashboard.html
{% include "inc/head.html" %}
<!-- START: site/dashboard -->
<!-- actions -->
<p class="buttons">
    <!-- senv.claim -->
    {% if site.env.claimed %}
    <a href="{% url 'site:release_confirm' site.name site.env.name %}">env.release</a>
    {% else %}
    <a href="{% url 'site:claim_confirm' site.name site.env.name %}" title="So you are the only one who can work on it.">env.claim</a>
    {% endif %}

    <!-- senv.lock -->
    <a href="{% url 'site:lock_confirm' site.name site.env.name %}" title="So nobody can work on it.">env.lock</a>

    {% if site.env.live %}
        <a href="{% url 'jobq:intcmd_confirm' site.name site.env.name 'env.live-unset' %}" title="So its special protection is removed.">env.live-unset</a>
    {% else %}
        <a href="{% url 'jobq:intcmd_confirm' site.name site.env.name 'env.live-set' %}" title="So it's protected a bit more.">env.live-set</a>
    {% endif %}
</p>

<!-- info -->
<p>
    <br>
    <b>Server:</b> <a href="{% url 'slave:dashboard' site.env.host_slug %}">{{site.env.host}}</a>
</p>
<hr>

<!-- jobq log -->
<div id="jobq-log">
    <p>
        <h3><a name="activity-log">Env Log</a></h3> - <a href="{% url 'site:log' site.name site.env.name %}#jobq-log">site log</a>
    </p>
    <table>
        <tr>
            <th class="left">Date</th>
            <th class="left">Status</th>
            <th>Run Time</th>
            <th>User</th>
            <th class="right">Command</th>
            <th class="right">Full Info</th>
        </tr>
        {% for le in jobq.log %}
        <tr class="{{le.css_class}}">
            <td class="left">[{{le.date}}]</td>
            <td class="left">{{le.status}}</td>
            <td>{{le.cmd_took}}</td>
            <td>{{le.user}}</td>
            <td class="right"><a title="exit: {{le.cmd_exit}}">{{le.cmd_name}}</a></td>
            <td class="right"><a title="full info" href="{% url 'jobq:info' site.name site.env.name le.id %}">{{le.id_slug}}</a></td>
        </tr>
        {% endfor %}
    </table>
</div>
<!-- END: site/dashboard -->
{% include "inc/tail.html" %}

templates/site/index.html
{% include "inc/head.html" %}
<!-- START: index -->
<p>{{sites_no}} sites - {{envs_no}} environments</p>

<form action="{% url 'site:envRedir' %}" method="post">
Choose environment: <input name="tsadmEnvRedir" list="site-envs-list" required="required">
<datalist id="site-envs-list">
{% for s in se_all %}{% for e in s.envs %}
    <option value="{{s.name}}.{{e.name}}">{{s.name}}.{{e.name}}</option>
{% endfor %}{% endfor %}
</datalist>
<input type="submit" value="Go!">
</form>

<ul class="site-index">
{% for s in se_all %}
    <li><span class="site-name">{{ s.name }}</span>
        <ul>
        {% if s.parent_site %}
            <li>child installation of: <span class="site-name">{{s.parent_site.name}}</span></li>
        {% endif %}
        {% for e in s.envs %}
            <li>
                <span class="env-name">{{e.name}}:</span> <a href="{% url 'site:dashboard' s.name e.name %}">{{s.name}}.{{e.name}}</a>
                {% if e.live %}
                    <b>[live] </b>
                {% endif %}
                {% if e.locked %}
                    <span>--- </span><i>locked</i> by {{e.locked_by}}
                {% elif e.claimed %}
                    <span>--- </span><i>claimed</i> by {{e.claimed_by}}
                {% endif %}
            </li>
        {% endfor %}
        </ul>
    </li>
{% endfor %}
</ul>
<!-- END: index -->
{% include "inc/tail.html" %}

templates/site/lock_confirm.html
{% include "inc/head.html" %}
<!-- START: site/lock_confirm -->
<p>Confirm locking <b>{{site.name}}.{{site.env.name}}</b> environment: <a href="{% url 'site:lock' site.name site.env.name lock.jobr_id %}">lock.confirm</a></p>
<!-- END: site/lock_confirm -->
{% include "inc/tail.html" %}

templates/site/locked.html
{% include "inc/head.html" %}
<!-- START: site/locked -->
<p><b>{{site.name}}.{{site.env.name}}</b> is LOCKED</p>
<p><a href="{% url 'site:unlock_confirm' site.name site.env.name %}">env.unlock</a></p>
<!-- END: site/locked -->
{% include "inc/tail.html" %}

templates/site/log.html
{% include "inc/head.html" %}
<!-- START: site/log -->
<div id="jobq-log">
    <p>
        <h3>{{site.name}} activity log</h3>
        <table>
            <tr>
                <th class="left">Date</th>
                <th class="left">Status</th>
                <th>Run Time</th>
                <th>User</th>
                <th class="right">Env</th>
                <th class="right">Command</th>
                <th class="right">Full Info</th>
            </tr>
        {% for le in site.log %}
            <tr class="{{le.css_class}}">
                <td class="left">[{{le.date}}]</td>
                <td class="left">{{le.status}}</td>
                <td>{{le.cmd_took}}</td>
                <td>{{le.user_name}}</td>
                <td class="right">{{le.env_name}}</td>
                <td class="right"><a title="exit: {{le.cmd_exit}}">{{le.cmd_name}}</a></td>
                <td class="right"><a title="full info" href="{% url 'jobq:info' site.name le.env_name le.id %}">{{le.id_slug}}</a></td>
            </tr>
        {% endfor %}
        </table>
    </p>
</div>
<!-- END: site/log -->
{% include "inc/tail.html" %}

templates/site/navbar.html
<!-- START: sites/navbar -->
<li><a href="{% url 'site:dashboard' site.name site.env.name %}">dashboard</a></li>
<li><a href="{% url 'git:home' site.name site.env.name %}">git</a></li>
<li><a href="{% url 'rsync:home' site.name site.env.name %}">files</a></li>
<li><a href="{% url 'mysql:home' site.name site.env.name %}">database</a></li>
<li><a href="{% url 'help:site' site.name site.env.name %}">help</a></li>
<!-- END: sites/navbar -->

templates/site/navbar.info.html
<!-- START: sites/navbar.info -->
{% if site.load_navbar %}
<div class="site-info">
    <p><span class="site-env-name">{{site.name}}.{{site.env.name}}</span> - <a href="http://{{site.name}}{{site.env.name}}.{{site.env.domain}}/" target="_blank">view site</a> for this environment</p>
</div>
{% endif %}
<!-- END: sites/navbar.info -->

templates/site/release_confirm.html
{% include "inc/head.html" %}
<!-- START: site/release_confirm -->
<p>Confirm releasing <b>{{site.name}}.{{site.env.name}}</b> environment: <a href="{% url 'site:release' site.name site.env.name jobr_id %}">release.confirm</a></p>
<!-- END: site/release_confirm -->
{% include "inc/tail.html" %}

templates/site/unlock_confirm.html
{% include "inc/head.html" %}
<!-- START: site/unlock_confirm -->
<p>Confirm unlocking <b>{{site.name}}.{{site.env.name}}</b> environment: <a href="{% url 'site:unlock' site.name site.env.name unlock.jobr_id %}">unlock.confirm</a></p>
<!-- END: site/unlock_confirm -->
{% include "inc/tail.html" %}