tsadm/git/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('',
    url(r'^(\w+)/(\w+)/$', 'tsadm.git.views.home', name='home'),
    url(r'^hook/post-receive/$', 'tsadm.git.views.post_receive', name='post_receive'),
)

tsadm/site/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('',
    url(r'^admin/$', 'tsadm.site.views.admin', name='admin'),

    url(r'^index/$', 'tsadm.site.views.index', name='index'),
    url(r'^(\w+)/(\w+)/$', 'tsadm.site.views.dashboard', name='dashboard'),

    url(r'^(\w+)/(\w+)/log/$', 'tsadm.site.views.log', name='log'),

    url(r'^(\w+)/(\w+)/lock/$', 'tsadm.site.views.lock_confirm', name='lock_confirm'),
    url(r'^(\w+)/(\w+)/lock/([a-f0-9]+)/$', 'tsadm.site.views.lock', name='lock'),

    url(r'^(\w+)/(\w+)/unlock/$', 'tsadm.site.views.unlock_confirm', name='unlock_confirm'),
    url(r'^(\w+)/(\w+)/unlock/([a-f0-9]+)/$', 'tsadm.site.views.unlock', name='unlock'),

    url(r'^(\w+)/(\w+)/claim/$', 'tsadm.site.views.claim_confirm', name='claim_confirm'),
    url(r'^(\w+)/(\w+)/claim/([a-f0-9]+)/$', 'tsadm.site.views.claim', name='claim'),

    url(r'^(\w+)/(\w+)/release/$', 'tsadm.site.views.release_confirm', name='release_confirm'),
    url(r'^(\w+)/(\w+)/release/([a-f0-9]+)/$', 'tsadm.site.views.release', name='release'),

    url(r'^envRedir/$', 'tsadm.site.views.env_redir', name='envRedir'),
)

tsadm/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('',
    url(r'^$', 'tsadm.site.views.index', name='index'),
    url(r'^soft-info/$', 'tsadm.views.soft_info', name='soft-info'),

    url(r'^cmd/confirm/$', 'tsadm.views.cmd_confirm', name='cmd_confirm'),
    url(r'^cmd/exec/$', 'tsadm.views.cmd_exec', name='cmd_exec'),

    url(r'^admin/', include('tsadm.admin.urls', namespace='admin')),
    url(r'^site/', include('tsadm.site.urls', namespace='site')),
    url(r'^git/', include('tsadm.git.urls', namespace='git')),
    url(r'^files/', include('tsadm.rsync.urls', namespace='rsync')),
    url(r'^db/', include('tsadm._mysql.urls', namespace='mysql')),
    url(r'^jobq/', include('tsadm.jobq.urls', namespace='jobq')),
    url(r'^help/', include('tsadm.help.urls', namespace='help')),
    url(r'^user/', include('tsadm.user.urls', namespace='user')),
    url(r'^slave/', include('tsadm.slave.urls', namespace='slave')),
    url(r'^asb/', include('tsadm.ansible.urls', namespace='ansible')),
)

templates/inc/admin_navbar.html
<!-- START: adm/navbar -->
{% if user.is_site_admin %}
<li><a href="{% url 'admin:home' %}">admin</a></li>
<li><a href="{% url 'site:admin' %}">sites</a></li>
{% endif %}
{% if user.is_admin %}
<li><a href="{% url 'slave:admin' %}">servers</a></li>
<li><a href="{% url 'user:admin' %}">users</a></li>
{% endif %}
<!-- END: adm/navbar -->

templates/inc/debug.html
{% if debug %}
<div id="debug">
<pre>
{{debug.tmpl}}
</pre>
</div>
{% endif %}

templates/inc/head.html
<!-- START: head -->
<!DOCTYPE html>
<html>
    <head>
        <meta charset="{{charset}}">
        <base href="{{base_href}}" target="_self">
        <link rel="stylesheet" type="text/css" href="{{css_relpath}}?v={{css_version}}">
        <link type="image/x-icon" href="/static/favicon.ico" rel="shortcut icon">
        <title>{{appname}} - {{page.title}}</title>
    </head>
    <body>
        <div id="container">
            {% include "inc/navbar.html" %}
            <div id="content">
                {% include "inc/umesg.html" %}
<!-- END: head -->

templates/inc/navbar.html
<!-- START: navbar -->
<div id="navbar">
    <ul>
        <li class="appname">
            <b><a href="{% url 'index' %}">{{appname}}</a></b>
        </li>
        <li class="info">
            <p>
                {{date_time}}<br />
                {% if user %}
                <a class="user-name" href="{% url 'user:home' %}"><i>{{user.name}}</i></a>
                {% endif %}
            </p>
        </li>
        <li class="curpath">
            <p>
                {{page.title}}
            </p>
        </li>
    </ul>
    <div class="sep"></div>
    <br>
    <ul class="buttons">
    {% if site.load_navbar %}
        {% include "site/navbar.html" %}
    {% else %}
        {% include "inc/admin_navbar.html" %}
    {% endif %}
    </ul>
    <div class="sep"></div>
    {% include "site/navbar.info.html" %}
</div><!-- div: navbar -->
<hr class="sep">
<!-- END: navbar -->

templates/inc/regr_tests.html
{% if regr_tests %}
<!-- TSADM_REGR_TESTS:DATA:{{regr_tests.data}} -->
<!-- TSADM_REGR_TESTS:DIGEST:{{regr_tests.digest}} -->
{% endif %}

templates/inc/tail.html
<!-- START: tail -->
        </div><!-- div: content -->
        <div id="footer">
            <p>
                v{{version}}:{{took}}<br />
            {% if user.is_admin %}
                <a class="soft-info" title="software info" href="{% url 'soft-info' %}"><img src="/static/favicon.png" alt="-_-" style="width:16px;height:16px"></a>
            {% else %}
                <a class="soft-info" title="tsadm project" target="_blank" href="https://github.com/jctincan/tsadm-webapp"><img src="/static/favicon.png" alt="-_-" style="width:16px;height:16px"></a>
            {% endif %}
                {% include "inc/validator.html" %}
            </p>
        </div>
{% include "inc/regr_tests.html" %}
        </div><!-- div: container -->
        {% include "inc/debug.html" %}
    </body>
</html>
<!-- END: tail -->

templates/inc/umesg.html
<!-- START: inc/umesg -->
{% if umesg %}
<div id="umesg">
    <p>
        {% for line in umesg %}<span class="{{line.prio}}">[{{line.prio}}] {{line.mesg}}<br /></span>{% endfor %}
    </p>
</div>
{% endif %}
<!-- END: inc/umesg -->

templates/inc/validator.html
<!-- START: inc/validator -->
{% if devmode %}
<div id="w3-validator">
    <p class="inline">Validate:</p>
    <form class="inline" method="POST" enctype="multipart/form-data" action="http://validator.w3.org/check" target="tsadm-html-validator">
        <textarea hidden="hidden" name="fragment">[[TSADM_HTML_VALIDATE_CONTENT]]</textarea>
        <input type="hidden" name="charset" value="{{charset}}">
        <input type="hidden" name="doctype" value="HTML5">
        <input class="button" type="submit" value="HTML5">
    </form>
    <form class="inline" method="POST" enctype="multipart/form-data" action="http://jigsaw.w3.org/css-validator/validator" target="tsadm-css-validator">
        <textarea hidden="hidden" name="text">[[TSADM_CSS_VALIDATE_CONTENT]]</textarea>
        <input type="hidden" name="profile" value="css3">
        <input class="button" type="submit" value="CSS3">
    </form>
</div>
{% endif %}
<!-- END: inc/validator -->