tsadm/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('',
    url(r'^$', 'tsadm.site.views.index', name='index'),
    url(r'^soft-info/$', 'tsadm.views.soft_info', name='soft-info'),

    url(r'^cmd/confirm/$', 'tsadm.views.cmd_confirm', name='cmd_confirm'),
    url(r'^cmd/exec/$', 'tsadm.views.cmd_exec', name='cmd_exec'),

    url(r'^admin/', include('tsadm.admin.urls', namespace='admin')),
    url(r'^site/', include('tsadm.site.urls', namespace='site')),
    url(r'^git/', include('tsadm.git.urls', namespace='git')),
    url(r'^files/', include('tsadm.rsync.urls', namespace='rsync')),
    url(r'^db/', include('tsadm._mysql.urls', namespace='mysql')),
    url(r'^jobq/', include('tsadm.jobq.urls', namespace='jobq')),
    url(r'^help/', include('tsadm.help.urls', namespace='help')),
    url(r'^user/', include('tsadm.user.urls', namespace='user')),
    url(r'^slave/', include('tsadm.slave.urls', namespace='slave')),
    url(r'^asb/', include('tsadm.ansible.urls', namespace='ansible')),
)

tsadm/user/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('',
    url(r'^$', 'tsadm.user.views.home', name='home'),

    url(r'^addkey/$', 'tsadm.user.views.addkey', name='addkey'),
    url(r'^showkey/([a-zA-Z0-9:]+)/$', 'tsadm.user.views.showkey', name='showkey'),
    url(r'^delkey/([a-zA-Z0-9:]+)/$', 'tsadm.user.views.delkey', name='delkey'),

    url(r'^admin/$', 'tsadm.user.views.admin', name='admin'),
)

tsadm/user/views.py
import time
from django.shortcuts import render, redirect

from tsadm.wapp import TSAdmWApp
wapp = TSAdmWApp()


def home(req):
    if not wapp.start(req, '__user/home'):
        return wapp.error_page()
    tmpl_data = wapp.tmpl_data()
    return render(req, 'user/home.html', wapp.end(tmpl_data))


def admin(req):
    if not wapp.start(req, '__user/admin', acclvl='ADMIN'):
        return wapp.error_page()
    tmpl_data = wapp.tmpl_data()
    users_all = list()
    for u in wapp.db.user_all():
        u['last_seen'] = time.strftime(wapp.conf.get('CUR_TIME_FMT'), time.localtime(u['last_seen']))
        users_all.append(u)
    tmpl_data['users_all'] = users_all
    return render(req, 'user/admin.html', wapp.end(tmpl_data))


def addkey(req):
    if not wapp.start(req, '__user/addkey'):
        return wapp.error_page()

    wapp.log.dbg('req.POST:', req.POST)
    tsadm_cmd = req.POST.get('tsadm_cmd', None)

    if tsadm_cmd == 'userAddKey':
        input_ok = True
        key_name = req.POST.get('tsadm_user_key_name', None)
        key_text = req.POST.get('tsadm_user_key_text', None)

        if key_name is None or key_name == '':
            wapp.umesg.err('key name not provided')
            input_ok = False
        else:
            key_name = key_name.strip()
            wapp.log.dbg('user key name:', key_name)

        if key_text is None or key_text == '':
            wapp.umesg.err('key not provided')
            input_ok = False
        elif len(key_text.splitlines()) > 1:
            wapp.umesg.err('the key text contains more than one line')
            input_ok = False
        else:
            key_text = key_text.strip()
            wapp.log.dbg('user key text:', key_text)

        if input_ok:
            try:
                import_ok, err_msg = wapp.user.auth_key_import(key_name, key_text)
            except Exception as e:
                return wapp.error_page(500, str(e))
            else:
                if import_ok:
                    wapp.umesg.inf('key "'+key_name+'" added')
                else:
                    wapp.umesg.err('adding key "'+key_name+'" failed!')
                    wapp.umesg.err(err_msg)

    tmpl_data = wapp.tmpl_data()
    return render(req, 'user/addkey.html', wapp.end(tmpl_data))


def showkey(req, kfprint):
    if not wapp.start(req, '__user/showkey'):
        return wapp.error_page()
    tmpl_data = wapp.tmpl_data()
    tmpl_data['userAuthKey'] = wapp.db.user_auth_getkey(wapp.user.id, kfprint)
    if tmpl_data['userAuthKey'] is None:
        return wapp.error_page(400, 'invalid key')
    return render(req, 'user/showkey.html', wapp.end(tmpl_data))


def delkey(req, kfprint):
    if not wapp.start(req, '__user/delkey'):
        return wapp.error_page()
    tmpl_data = wapp.tmpl_data()
    tmpl_data['userAuthKey'] = wapp.db.user_auth_getkey(wapp.user.id, kfprint)
    if tmpl_data['userAuthKey'] is None:
        return wapp.error_page(400, 'invalid key')
    delConfirm = req.GET.get('tsadmConfirmRemove', None)
    if delConfirm is None:
        return render(req, 'user/delkey.html', wapp.end(tmpl_data))
    else:
        try:
            wapp.db.user_auth_delkey(wapp.user.id, kfprint)
        except Exception as e:
            return wapp.error_page(500, str(e))
        else:
            wapp.umesg.inf('auth key '+tmpl_data['userAuthKey']['key_name']+' removed!')
            tmpl_data['userAuthKey'] = '__removed__'
        return render(req, 'user/delkey.html', wapp.end(tmpl_data))

templates/user/addkey.html
{% include "inc/head.html" %}
<p>
    <form action="{% url 'user:addkey' %}" method="post">
        <label for="key-name">key name:</label>
        <input type="text" value="" id="key-name" name="tsadm_user_key_name" required="required">
        <br>

        public key (one line):<br>
        <textarea id="key-text" name="tsadm_user_key_text" style="width:40%; height:20em;" required="required"></textarea>
        <br>
        <br>

        <input type="hidden" name="tsadm_cmd" value="userAddKey">
        <input class="button" type="submit" value="save">

        <a class="button" href="{% url 'user:home' %}">cancel</a>
    </form>
</p>
{% include "inc/tail.html" %}

templates/user/admin.html
{% include "inc/head.html" %}
<!-- START: user/admin -->
<div>
    <p>
    {% for user in users_all %}
        <b>Name:</b> {{user.name}}<br>
        <b>Access level:</b> {{user.acclvl}}<br>
        <b>Devel environment:</b> {{user.setenv_devel}}<br>
        <b>Last seen:</b> {{user.last_seen}}
        <hr>
    {% endfor %}
    </p>
</div>
<!-- END: user/admin -->
{% include "inc/tail.html" %}

templates/user/delkey.html
{% include "inc/head.html" %}
{% if userAuthKey != '__removed__' %}
<p>
    <b>Are you sure you want to remove the following SSH key?</b>
    <a href="{% url 'user:delkey' userAuthKey.fingerprint %}?tsadmConfirmRemove">remove</a>
    - <a href="{% url 'user:home' %}">cancel</a>
</p>
<p>
    {{userAuthKey.key_name}}
    {{userAuthKey.fingerprint}}
    {{userAuthKey.key_bits}}
    {{userAuthKey.key_protocol}}
</p>
{% endif %}
{% include "inc/tail.html" %}

templates/user/home.html
{% include "inc/head.html" %}
<!-- START: user/home -->
<p>
    <b>Valid until:</b> {{user.cert.until}}
    <br><b>Access level:</b> {{user.acclvl}}
    <br><b>Fingerprint:</b> {{user.cert.fingerprint}}
    <br><b>Devel environment:</b> {% if user.setenv_devel == "1" %}enabled{% else %}disabled{% endif %}
</p>

<!-- SSH keys -->
<p>
    <b>SSH keys</b> - <a href="{% url 'user:addkey' %}">add new</a>
    <br>

{% for authKey in user.auth_keys %}
    <a href="{% url 'user:showkey' authKey.fingerprint %}">{{authKey.key_name}}</a>
    {{authKey.fingerprint}}
    {{authKey.key_protocol}}
    {{authKey.key_bits}}
    - <a href="{% url 'user:delkey' authKey.fingerprint %}">remove</a>
    <br>
{% endfor %}

</p>

<!-- END: user/home -->
{% include "inc/tail.html" %}

templates/user/showkey.html
{% include "inc/head.html" %}
<p>
    {{userAuthKey.key_name}}
    {{userAuthKey.fingerprint}}
    {{userAuthKey.key_bits}}
    {{userAuthKey.key_protocol}}
    <br>
    <br>
    {{userAuthKey.ssh_key}}
</p>
{% include "inc/tail.html" %}